project:
  type: website
  output-dir: build
  render:
    - "*.qmd"
    - "!bibliography.qmd"

website:
  title: "Sample Project"
  search: true
  sidebar:
    style: "floating"
    search: true
    contents:
      - index.qmd
      - project_charta.qmd
      - data_report.qmd
      - modelling_report.qmd
      - evaluation.qmd
      - meeting_notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  
  pdf:
    documentclass: scrreprt
    number-sections: true